---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Get installed graphviz version.
  command:  dot -V
  changed_when: false
  failed_when: false
  check_mode: false
  register: dot_installed_version

- name: Flag wrong graphviz version
  include_tasks: build.yml
  when:
    - (dot_installed_version.rc != 0) or (dot_installed_version.stdout | regex_replace("^dot - graphviz version ([0-9\.]+) [\s\S]*$", "\\1") is not match(graphviz_version))

